version: "3.9"

services:
  backend:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
      #    depends_on:
      #      db:
      #        condition: service_healthy
    tty: true
    restart: always

    #  db:
    #    image: mysql
    #    restart: always
    #    environment:
    #      MYSQL_ROOT_PASSWORD: mysql
    #    volumes:
    #      - db:/var/lib/mysql
    #    healthcheck:
    #      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 2
    #      start_period: 0s
    #
    #volumes:
    #  db:
