---
services:
  api:
    build: .
    tty: true
    restart: always
    environment:
      - DATABASE_URL=sqlite:////var/lib/bookclub/bookclub.db
    volumes:
      - db:/var/lib/bookclub
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=strip-api-prefix"

  traefik:
    image: traefik:v3.2
    ports:
      # HTTPS
      - 127.0.0.1:4430:4430

      # Traefik Dashboard
      - 127.0.0.1:8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.entryPoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicAuth.users=admin:$$apr1$$FkSY0vIa$$w5n3MStAK5qPzQgevk1b10"
    volumes:
      # Scary! But should be ok for us
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - type: bind
        source: traefik/traefik.toml
        target: /etc/traefik/traefik.toml

volumes:
  db:
