---
services:
  api:
    build: .
    tty: true
    restart: always
    environment:
      - DATABASE_URL=sqlite:////var/lib/bookclub/bookclub.db
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    volumes:
      - db:/var/lib/bookclub
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.savagepastaman.com`)"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=strip-api-prefix"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v3.2
    ports:
      # HTTPS
      - 127.0.0.1:4430:4430
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL=${TLS_EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.savagepastaman.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$FkSY0vIa$$w5n3MStAK5qPzQgevk1b10"

    volumes:
      # Scary! But should be ok for us
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # ACME Certificates
      - tls:/letsencrypt

      - type: bind
        source: traefik/traefik.toml
        target: /etc/traefik/traefik.toml

volumes:
  db:
  tls:
