services:
  backend:
    build: .
      #    depends_on:
      #      db:
      #        condition: service_healthy
    tty: true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"

      # We'll replace this later with our own domain
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"

  reverse-proxy:
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # Scary! But should be ok for us
      - /var/run/docker.sock:/var/run/docker.sock:ro

    #  db:
    #    image: mysql
    #    restart: always
    #    environment:
    #      MYSQL_ROOT_PASSWORD: mysql
    #    volumes:
    #      - db:/var/lib/mysql
    #    healthcheck:
    #      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    #      interval: 5s
    #      timeout: 3s
    #      retries: 2
    #      start_period: 0s
    #
    #volumes:
    #  db:
