---
services:
  # api:
  #   build: .
  #   tty: true
  #   restart: always
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.api.entrypoints=web
  #
  #     # We'll replace this later with our own domain
  #     - traefik.http.routers.api.rule=Host(`api.localhost`)

  traefik:
    image: traefik:v3.2
    ports:
      - 127.0.0.1:4430:4430
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicAuth.users=admin:$$apr1$$FkSY0vIa$$w5n3MStAK5qPzQgevk1b10"
    volumes:
      # Scary! But should be ok for us
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - type: bind
        source: traefik/traefik.toml
        target: /etc/traefik/traefik.toml
