accesslog = true
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.traefik]
  address = ":8080"

  [entryPoints.https]
  address = ":4430"

[api]
dashboard = true
insecure = false

[log]
level = "INFO"

[providers.docker]
exposedByDefault = false
